import type { AppData } from '../types.js';
import { store } from '../data/store.js';
import { backendConfigured, runtimeConfig } from '../services/config.js';
import { clearSession, getSession, signIn, signUp } from '../services/auth.js';
import { pullState, pushState } from '../services/sync.js';

export class SettingsScreen extends React.Component<{data:AppData;onRefresh:()=>void;onToast:(m:string,t?:'neutral'|'success'|'error')=>void},any>{
  constructor(props:any){super(props);const s=getSession();this.state={protein:String(props.data.settings.proteinGoalG),fiber:String(props.data.settings.fiberGoalG),email:s?.email??'',password:'',authMode:'signin',authBusy:false,authError:'',session:s,syncBusy:false};}
  async saveGoals(){const p=Number(this.state.protein),f=Number(this.state.fiber);if(!Number.isFinite(p)||p<=0||!Number.isFinite(f)||f<=0){this.props.onToast('Goals must be positive numbers.','error');return;}await store.setSettings({proteinGoalG:p,fiberGoalG:f});this.props.onToast('Nutrition display preferences saved.','success');}
  exportData(){const blob=new Blob([JSON.stringify(store.exportData(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nourish-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async importFile(file?:File){if(!file)return;try{const text=await file.text();const parsed=JSON.parse(text);if(!parsed||parsed.schemaVersion!==1||!Array.isArray(parsed.meals)||!Array.isArray(parsed.foods))throw new Error('This does not look like a Nourish backup.');await store.importData(parsed);this.props.onRefresh();this.props.onToast('Backup imported locally.','success');}catch(e){this.props.onToast(e instanceof Error?e.message:'Could not import backup.','error');}}
  async auth(){try{this.setState({authBusy:true,authError:''});if(this.state.authMode==='signup'){const result=await signUp(this.state.email,this.state.password);this.setState({session:result.session,authBusy:false});this.props.onToast(result.message,'success');}else{const session=await signIn(this.state.email,this.state.password);this.setState({session,authBusy:false});this.props.onToast('Signed in. Local data stays on this device until you choose Sync now.','success');}}catch(e){this.setState({authBusy:false,authError:e instanceof Error?e.message:'Authentication failed.'});}}
  async syncNow(){try{this.setState({syncBusy:true});await pushState(store.exportData());this.props.onToast('Encrypted transport completed; your JSON state is stored in your user-scoped Supabase row.','success');}catch(e){this.props.onToast(e instanceof Error?e.message:'Sync failed.','error');}finally{this.setState({syncBusy:false});}}
  async pull(){try{this.setState({syncBusy:true});const cloud=await pullState();if(!cloud){this.props.onToast('No cloud state exists yet.','neutral');return;}if(!confirm('Replace this device’s local state with the cloud copy? Export a backup first if you are unsure.'))return;await store.importData(cloud);this.props.onRefresh();this.props.onToast('Cloud state restored to this device.','success');}catch(e){this.props.onToast(e instanceof Error?e.message:'Cloud restore failed.','error');}finally{this.setState({syncBusy:false});}}
  render(){const cfg=runtimeConfig();const configured=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);const session=this.state.session;return <div className="page"><header className="page-heading"><div><div className="eyebrow">Settings</div><h1>Control what the app knows</h1><p>Local-first by default. Cloud sync, AI, and photo processing are opt-in capabilities that require explicitly configured services.</p></div></header>
    <div className="settings-grid">
      <section className="settings-section"><header><div><h2>Nutrition display</h2><p>These are display goals, not judgments or automatic restriction targets.</p></div></header><label className="toggle-row"><span><strong>Show energy</strong><small>Hide calories from the Today screen without deleting nutrition data.</small></span><input type="checkbox" checked={this.props.data.settings.showEnergy} onChange={async(e:any)=>{await store.setSettings({showEnergy:e.target.checked});this.props.onRefresh();}}/></label><div className="form-grid two"><label><span>Protein goal</span><div className="input-unit"><input type="number" min="1" value={this.state.protein} onChange={(e:any)=>this.setState({protein:e.target.value})}/><b>g</b></div></label><label><span>Fiber goal</span><div className="input-unit"><input type="number" min="1" value={this.state.fiber} onChange={(e:any)=>this.setState({fiber:e.target.value})}/><b>g</b></div></label></div><button className="button button-secondary" onClick={()=>this.saveGoals()}>Save display goals</button></section>

      <section className="settings-section"><header><div><h2>Privacy & photos</h2><p>Meal photos are resized and metadata-stripped before AI processing. They are not retained by the app by default.</p></div></header><label className="toggle-row"><span><strong>Keep meal photos</strong><small>Not implemented in V1; intentionally disabled until private storage retention controls are verified.</small></span><input type="checkbox" disabled checked={false}/></label><div className="status-list"><div><span>Local database</span><b className="status-ok">Active</b></div><div><span>Gemini backend</span><b className={backendConfigured()?'status-ok':'status-muted'}>{backendConfigured()?'Configured':'Not configured'}</b></div><div><span>Browser secrets</span><b className="status-ok">None required</b></div></div></section>

      <section className="settings-section"><header><div><h2>Backup</h2><p>Keep a portable copy independent of any API provider.</p></div></header><div className="button-row"><button className="button button-secondary" onClick={()=>this.exportData()}>Export JSON</button><label className="button button-quiet file-button">Import JSON<input type="file" accept="application/json,.json" onChange={(e:any)=>this.importFile(e.target.files?.[0])}/></label></div><small className="fine-print">Backups include your food log and nutrition data. Store them somewhere appropriate for personal health-related information.</small></section>

      <section className="settings-section"><header><div><h2>Optional Supabase sync</h2><p>Authentication and row-level security isolate each user. The app works entirely locally when this is not configured.</p></div></header>{!configured?<div className="callout"><strong>Supabase not configured</strong><span>Add the public project URL and anon key at deployment. Private service-role keys never belong in the browser.</span></div>:session?<div className="signed-in-wrap"><div className="signed-in"><span>Signed in as</span><strong>{session.email??session.userId}</strong></div><div className="button-row"><button className="button button-primary" disabled={this.state.syncBusy} onClick={()=>this.syncNow()}>{this.state.syncBusy?'Working…':'Sync now'}</button><button className="button button-quiet" disabled={this.state.syncBusy} onClick={()=>this.pull()}>Restore from cloud</button><button className="text-button danger" onClick={()=>{clearSession();this.setState({session:null});}}>Sign out</button></div></div>:<div className="auth-box"><div className="segmented"><button className={this.state.authMode==='signin'?'active':''} onClick={()=>this.setState({authMode:'signin'})}>Sign in</button><button className={this.state.authMode==='signup'?'active':''} onClick={()=>this.setState({authMode:'signup'})}>Create account</button></div><label><span>Email</span><input type="email" autoComplete="email" value={this.state.email} onChange={(e:any)=>this.setState({email:e.target.value})}/></label><label><span>Password</span><input type="password" minLength={8} autoComplete={this.state.authMode==='signin'?'current-password':'new-password'} value={this.state.password} onChange={(e:any)=>this.setState({password:e.target.value})}/></label>{this.state.authError?<div className="inline-error">{this.state.authError}</div>:null}<button className="button button-primary" disabled={this.state.authBusy} onClick={()=>this.auth()}>{this.state.authBusy?'Working…':this.state.authMode==='signin'?'Sign in':'Create account'}</button></div>}</section>
    </div>
  </div>;}
}
